name = "lifeguard"
version = "1.1.0"
description = "A simple actor pool for Gleam!"
licences = ["MIT"]
repository = { type = "github", user = "Pevensie", repo = "lifeguard" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.51.0 and < 2.0.0"
gleam_deque = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
gleam_otp = ">= 0.16.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
